### ISSUE TITLE
Upper limit on dataset size?

### ISSUE THREAD

**Issue by rybesh** [pelagios/peripleo-lite#11]
What's a reasonable upper limit on the size of dataset Peripleo Lite can handle?

**Comment by rsimon** [comment]
That's a bit hard to say because a) different browsers will have different limits for when things get sluggish, b) it also depends on what your records look like. (More freetext, for example, will lead to longer download and indexing time.)

What's (probably) least criticial is number of rendered markers on the map. FWIW: I've used ~40k records with fairly good performance so far.

**Comment by rybesh** [comment]
Great, thank you!
